spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: payments
  liquibase:
    change-log: classpath:liquibase/changelog/master.xml
    enabled: true
    default-schema: payments
  kafka:
    bootstrap-servers: localhost:9092
    group-id: payment-processor-group
    topics:
      payment-requests: payment-requests
      payment-responses: payment-responses

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.payment: DEBUG 