spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog/master.xml
    enabled: true
    default-schema: payments
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    group-id: payment-processor-group
    topics:
      payment-requests: payment-requests
      payment-responses: payment-responses

server:
  port: 8082

logging:
  level:
    org.springframework: INFO
    com.payment: DEBUG 